{% set name = "datamol" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datamol-{{ version }}.tar.gz
  sha256: f748d76ff0c8bc6963eb55a0c7ea280248b0ead6f5cad27cd742d83e32e8f2d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - pip
    - tqdm
    - loguru
    - joblib
    - platformdirs
    - fsspec >=2021.9
    - packaging
    - typing_extensions
    - importlib_resources

    # Scientific
    - pandas
    - numpy
    - scipy
    - pillow
    - matplotlib-base
    - scikit-learn

    # Chemistry
    - rdkit >=2021.09
    - selfies

test:
  imports:
    - datamol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/datamol-io/datamol
  summary: A python library to work with molecules. Built on top of RDKit.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
