{% set name = "datamol" %}
{% set version = "0.4.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datamol-{{ version }}.tar.gz
  sha256: 5a2923f7e75293351b4c3b9e835247956f19f6cdf8879536d578b3e465127fa6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - pip
    - tqdm
    - loguru
    - joblib
    - fsspec >=2021.6

    # Scientific
    - pandas
    - numpy
    - scipy
    - pillow
    - matplotlib-base

    # Chemistry
    - rdkit >=2020.09
    - selfies

test:
  imports:
    - datamol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/datamol-org/datamol
  summary: A python library to work with molecules. Built on top of RDKit.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
