{% set name = "datamol" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/datamol-{{ version }}.tar.gz
  sha256: 20ee2c21c46c82902810a95d1d1054ad85dda84213b10a22269601f67ae7ad72

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - fsspec >=0.8.0
    - joblib
    - loguru
    - numpy
    - pandas
    - pillow
    - python >=3.7
    - scipy
    - selfies
    - tqdm
    - rdkit >=2020.09

test:
  imports:
    - datamol
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/datamol-org/datamol
  summary: A python library to work with molecules. Built on top of RDKit.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - maclandrol
